attribute_mapping:
  cn: cn
  displayName: displayName
  givenName: givenName
  mail: mail
  sn: sn
  uid: sAMAccountName

user_objectclass:
  - inetOrgPerson
  - inetUser
  - organizationalPerson
  - person
  - top

user_rdn: uid
